server:
  port: 18888
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1020548332803-a811bp7gehd949ft1p5chjsndcap695e.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/test/oauth2/callback/{registrationId}"
    user:
      name: user1
      password: 1111
      roles: USER
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/test/temp/h2db/rememberme
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update